// 20240716113736
// https://api.freeapi.app/api/v1/public/meals?page=1&limit=100

export const resList = [

  {
    idMeal: "52773",
    strMeal: "Honey Teriyaki Salmon",
    strDrinkAlternate: null,
    strCategory: "Seafood",
    strArea: "Japanese",
    strInstructions:
      "Mix all the ingredients in the Honey Teriyaki Glaze together. Whisk to blend well. Combine the salmon and the Glaze together.\r\n\r\nHeat up a skillet on medium-low heat. Add the oil, Pan-fry the salmon on both sides until it’s completely cooked inside and the glaze thickens.\r\n\r\nGarnish with sesame and serve immediately.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg",
    strTags: "Fish,Breakfast,DateNight",
    strYoutube: "https://www.youtube.com/watch?v=4MpYuaJsvRw",
    strIngredient1: "Salmon",
    strIngredient2: "Olive oil",
    strIngredient3: "Soy Sauce",
    strIngredient4: "Sake",
    strIngredient5: "Sesame Seed",
    strIngredient6: "",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: "1 lb",
    strMeasure2: "1 tablespoon",
    strMeasure3: "2 tablespoons",
    strMeasure4: "2 tablespoons",
    strMeasure5: "4 tablespoons",
    strMeasure6: "",
    strMeasure7: "",
    strMeasure8: "",
    strMeasure9: "",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: null,
    strMeasure17: null,
    strMeasure18: null,
    strMeasure19: null,
    strMeasure20: null,
    strSource: null,
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strRating: "8.8",
    id: 8,
  },


  {
    idMeal: "52954",
    strMeal: "Hot and Sour Soup",
    strDrinkAlternate: null,
    strCategory: "Pork",
    strArea: "Chinese",
    strInstructions:
      "STEP 1 - MAKING THE SOUP\r\nIn a wok add chicken broth and wait for it to boil.\r\nNext add salt, sugar, sesame seed oil, white pepper, hot pepper sauce, vinegar and soy sauce and stir for few seconds.\r\nAdd Tofu, mushrooms, black wood ear mushrooms to the wok.\r\nTo thicken the sauce, whisk together 1 Tablespoon of cornstarch and 2 Tablespoon of water in a bowl and slowly add to your soup until it's the right thickness.\r\nNext add 1 egg slightly beaten with a knife or fork and add it to the soup and stir for 8 seconds\r\nServe the soup in a bowl and add the bbq pork and sliced green onions on top.",
    strMealThumb: "https://www.themealdb.com/images/media/meals/1529445893.jpg",
    strTags: "Soup",
    strYoutube: "https://www.youtube.com/watch?v=KgV9Zq3aSTo",
    strIngredient1: "Mushrooms",
    strIngredient2: "Wood Ear Mushrooms",
    strIngredient3: "Tofu",
    strIngredient4: "Pork",
    strIngredient5: "Chicken Stock",
    strIngredient6: "Salt",
    strIngredient7: "Sugar",
    strIngredient8: "Sesame Seed Oil",
    strIngredient9: "Pepper",
    strIngredient10: "Hotsauce",
    strIngredient11: "Vinegar",
    strIngredient12: "Soy Sauce",
    strIngredient13: "Cornstarch",
    strIngredient14: "Water",
    strIngredient15: "Spring Onions",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1/3 cup",
    strMeasure2: "1/3 cup",
    strMeasure3: "2/3 Cup",
    strMeasure4: "1/2 cup ",
    strMeasure5: "2-1/2 cups",
    strMeasure6: "1/2 tsp",
    strMeasure7: "1/4 tsp",
    strMeasure8: "1 tsp ",
    strMeasure9: "1/4 tsp",
    strMeasure10: "1/2 tsp",
    strMeasure11: "1-½ cups",
    strMeasure12: "1 tsp ",
    strMeasure13: "1 tbs",
    strMeasure14: "2 tbs",
    strMeasure15: "1/4 cup",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://sueandgambo.com/pages/chinese-hot-and-sour-soup",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strRating: "3.4",
    id: 10,
  },
];
